# Generated by Django 4.2.3 on 2023-07-18 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowings", "0002_alter_borrowing_actual_return_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="date",
            new_name="borrow_date",
        ),
    ]
